interface IIntroScreenProps {
  onStart: () => void;
}

export function IntroScreen({ onStart }: IIntroScreenProps) {
  return (
    <div className="mx-auto flex max-w-2xl flex-col items-center gap-6 py-24 text-center">
      <span className="rounded-full bg-indigo-100 px-3 py-1 text-xs font-medium text-indigo-700">
        Agentic Engineering Copilot
      </span>
      <h1 className="text-4xl font-bold text-slate-900">AI Product Factory</h1>
      <p className="text-lg text-slate-600">
        Turn a raw business idea into an implementation-ready MVP blueprint:
        Product Spec, Architecture, Security, Roadmap, Tasks, and a Readiness
        Score — generated by a multi-agent workflow with a human approval
        checkpoint.
      </p>
      <button
        type="button"
        onClick={onStart}
        className="rounded-md bg-indigo-600 px-6 py-3 text-sm font-semibold text-white hover:bg-indigo-700"
      >
        Start with a business idea
      </button>
      <p className="text-xs text-slate-400">
        Demo mode — deterministic output, no live LLM calls.
      </p>
    </div>
  );
}
